@startditaa
                             Server
                                |
                                v
                          +-----+----+
                          | socket() |
                          +-----+----+
                                |
                                v
                          +-----+----+
                          | bind()   |
                          +-----+----+
                        +-------|----------------+
                        :       v                :
   Client               | +-----+----+           |
      |                 | | listen() | only in   |
      v                 | +-----+----+ connection|
+-----+----+            |       |      oriented  |
| socket() |            |       v      protocols |
+----+-----+            | +-----+----+ (e.g. TCP)|
      |                 | | accept() |           |
      |                 | +-----+----+           |
      |                 +-------|----------------+
      |                         |
      v                         v
+-----+-----+  connection    block until
| connect() | -------------> connection
+-----+-----+  established   from client
      |                         |
      v                         v
+-----+----+   request    +-----+----+
| write()  | -----------> | read()   |
+-----+----+              +-----+----+
      |                         |
      v                         v
+-----+----+    reply     +-----+----+
| read()   | <----------- | write()  |
+-----+----+              +-----+----+
      |                         |
      v                         v
+-----+----+              +-----+----+
| close()  |              | close()  |
+----------+              +----------+
@endditaa
