version: 2.1

jobs:
  build_gatsby_page:
    docker:
      - image: cypress/included:10.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: apt update && apt install -y git procps && git --version
      - run: git config --global user.name "circleci (Lukas Woodtli)" &&  git config --global user.email lukas_woodtli@circleci.example.com
      - run:
          name: Build Gatsby Web Page
          command: NODE_OPTIONS=--max_old_space_size=4096 GATSBY_CPU_COUNT=1 npm run build
      - run:
          name: Run Gatsby Web Page Unit Tests
          command: npm test
      - run:
          name: Run Gatsby Web Page e2e Tests
          command: NODE_OPTIONS=--max_old_space_size=4096 GATSBY_CPU_COUNT=1 npm run e2e:ci

workflows:
  build-page:
    jobs:
      - build_gatsby_page
