version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.7
    working_directory: ~/WebPage
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: git config --global user.name "circleci (Lukas Woodtli)" &&  git config --global user.email lukas_woodtli@circleci.example.com
      - run:
          name: Build Web Page
          command: ./generate_page.py
workflows:
  build-page:
    jobs:
      - build
