name: Build and Test

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
     - '**'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        package-manager-cache: 'false'
    - name: Install node packages
      run: npm ci
    - name: Build
      run: npm run build
    - name: Unit Tests
      run: npm test
